/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 71681386d8316f709170f13717e76a20)
interface __BaseEnv_Env {
	AZURE_SPEECH_REGION: "japaneast";
	ALLOWED_ORIGIN: "https://ringhio-lab.github.io";
	AZURE_SPEECH_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AZURE_SPEECH_REGION" | "ALLOWED_ORIGIN" | "AZURE_SPEECH_KEY">> {}
}
